version: "3.9"

services:
  db:
    image: postgres:15
    container_name: crypto_app-db
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - crypto_network

  redis:
    image: redis:7
    container_name: crypto_app-redis
    ports:
      - "6379:6379"
    networks:
      - crypto_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_app-api
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
      - ./alembic:/app/alembic
    networks:
      - crypto_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001

volumes:
  db_data:

networks:
  crypto_network:
    driver: bridge
